//! Human-readable report builder.
//!
//! Converts the structured state artifacts (research_plan, trader_investment_plan,
//! risk_debate_state, final_trade_decision, portfolio_allocation, debate_state_artifact)
//! into a 9-section Markdown report and a styled HTML document.
//!
//! See `plan/P2-07-human-readable-report.md` for the full specification.

use chrono::Local;
use html_escape::encode_text;
use pulldown_cmark::{html, Options, Parser};
use serde_json::Value;

/// CSS injected into the generated HTML report.
const REPORT_CSS: &str = r#"
body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #1a1a1a; line-height: 1.5; }
h1 { border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }
h2 { color: #333; margin-top: 28px; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; }
th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
th { background-color: #f5f5f5; font-weight: 600; }
hr { border: none; border-top: 1px solid #e0e0e0; margin: 24px 0; }
strong { color: #1a1a1a; }
ul, ol { padding-left: 24px; }
"#;

/// Build a structured human-readable Markdown report from state artifacts.
///
/// Every section degrades gracefully when its source artifact is missing —
/// placeholders ("N/A", "No data available") are emitted instead of panicking.
pub fn build_human_readable_report(state: &Value) -> String {
    let date = state
        .get("current_date")
        .and_then(Value::as_str)
        .or_else(|| state.get("date").and_then(Value::as_str))
        .unwrap_or("N/A");
    let ticker = state
        .get("ticker")
        .and_then(Value::as_str)
        .or_else(|| {
            state
                .get("tickers")
                .and_then(Value::as_array)
                .and_then(|items| items.first())
                .and_then(Value::as_str)
        })
        .unwrap_or("N/A");
    let timestamp = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();

    let research = state.get("research_plan").unwrap_or(&Value::Null);
    let trader = state.get("trader_investment_plan").unwrap_or(&Value::Null);
    let final_decision = state.get("final_trade_decision").unwrap_or(&Value::Null);
    let allocation = state.get("portfolio_allocation").unwrap_or(&Value::Null);
    let risk_state = state.get("risk_debate_state").unwrap_or(&Value::Null);
    let debate = state.get("debate_state_artifact").unwrap_or(&Value::Null);

    let mut report = String::new();
    report.push_str(&format!("# {} Strategy Report — {}\n\n", ticker, date));

    // Section 1: Executive Summary
    report.push_str(&executive_summary(research, trader, final_decision));
    report.push_str("\n---\n\n");

    // Section 2: Investment Thesis
    report.push_str(&investment_thesis(research, final_decision));
    report.push_str("\n---\n\n");

    // Section 3: Bull Case
    report.push_str(&bull_case(debate));
    report.push_str("\n---\n\n");

    // Section 4: Bear Case
    report.push_str(&bear_case(debate));
    report.push_str("\n---\n\n");

    // Section 5: Risk Assessment
    report.push_str(&risk_assessment(risk_state, allocation));
    report.push_str("\n---\n\n");

    // Section 6: Trade Plan
    report.push_str(&trade_plan(trader, final_decision));
    report.push_str("\n---\n\n");

    // Section 7: Portfolio Allocation
    report.push_str(&portfolio_allocation(allocation));
    report.push_str("\n---\n\n");

    // Section 8: Confidence & Limitations
    report.push_str(&confidence_and_limitations(research));
    report.push_str("\n---\n\n");

    // Section 9: Next Steps
    report.push_str(&next_steps(research));
    report.push_str(&format!(
        "\n---\n*Generated by Akzio Signal Intelligence | {}*\n",
        timestamp
    ));

    report
}

fn executive_summary(research: &Value, trader: &Value, final_decision: &Value) -> String {
    let rating = research
        .get("rating")
        .and_then(Value::as_str)
        .or_else(|| final_decision.get("rating").and_then(Value::as_str))
        .unwrap_or("N/A");
    let long_prob = research
        .get("long_probability")
        .map(format_pct)
        .unwrap_or_else(|| "N/A".to_string());
    let short_prob = research
        .get("short_probability")
        .map(format_pct)
        .unwrap_or_else(|| "N/A".to_string());
    let rationale = research
        .get("probability_rationale")
        .and_then(Value::as_str)
        .unwrap_or("");
    let dominant_driver = research
        .get("dominant_driver")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    let why_now = research
        .get("why_now")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    let action = trader
        .get("action")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    let confidence_basis = research
        .get("confidence_basis")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty());
    let hold_reason = research
        .get("hold_reason")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty());
    let mut basis_summary = String::new();
    if let Some(value) = confidence_basis {
        basis_summary.push_str(&format!("Confidence basis: {value}\n"));
    }
    if let Some(value) = hold_reason {
        basis_summary.push_str(&format!("Hold reason: {value}\n"));
    }

    format!(
        "## 1. Executive Summary\n\n\
        Current rating: **{rating}** (long: {long_prob}, short: {short_prob}).\n\
        {basis_summary}\
        {rationale}\n\n\
        **Dominant Driver:** {dominant_driver}\n\
        **Why Now:** {why_now}\n\n\
        **Recommended Action:** {action}\n"
    )
}

fn investment_thesis(research: &Value, final_decision: &Value) -> String {
    let rating = final_decision
        .get("rating")
        .and_then(Value::as_str)
        .or_else(|| research.get("rating").and_then(Value::as_str))
        .unwrap_or("N/A");
    let horizon = final_decision
        .get("horizon")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    let long_prob = research
        .get("long_probability")
        .map(format_pct)
        .unwrap_or_else(|| "N/A".to_string());
    let short_prob = research
        .get("short_probability")
        .map(format_pct)
        .unwrap_or_else(|| "N/A".to_string());
    let rationale = research
        .get("probability_rationale")
        .and_then(Value::as_str)
        .unwrap_or("");
    let thesis = final_decision
        .get("investment_thesis")
        .and_then(Value::as_str)
        .filter(|text| !text.trim().is_empty())
        .unwrap_or("");

    let mut section = format!(
        "## 2. Investment Thesis\n\n\
        Rating: **{rating}** | Horizon: {horizon}\n\
        Probability: Long {long_prob} / Short {short_prob}\n\n\
        {rationale}\n"
    );
    if !thesis.is_empty() {
        section.push_str(&format!("\n{thesis}\n"));
    }
    section
}

fn bull_case(debate: &Value) -> String {
    let mut section = String::from("## 3. Bull Case\n\nTop bull evidence from debate:\n");

    // Forward-compatible direct field.
    if let Some(evidence) = debate.get("bull_evidence").and_then(Value::as_array) {
        if !evidence.is_empty() {
            for (i, evidence) in evidence.iter().take(3).enumerate() {
                let text = evidence
                    .as_str()
                    .or_else(|| evidence.get("point").and_then(Value::as_str))
                    .unwrap_or("(no description)");
                section.push_str(&format!("{}. {}\n", i + 1, text));
            }
            return section;
        }
    }

    // Extract from debate turns whose role contains "bull".
    let evidence = extract_debate_evidence(debate, "bull");
    if evidence.is_empty() {
        section.push_str("- No bull evidence recorded.\n");
    } else {
        for (i, text) in evidence.iter().take(3).enumerate() {
            section.push_str(&format!("{}. {}\n", i + 1, text));
        }
    }
    let quality = collect_evidence_quality(debate, "bull");
    if !quality.is_empty() {
        section.push_str("\n\n**Source Quality:**\n");
        section.push_str(&quality);
    }
    section
}

fn bear_case(debate: &Value) -> String {
    let mut section = String::from("## 4. Bear Case\n\nTop bear evidence from debate:\n");

    // Forward-compatible direct field.
    if let Some(evidence) = debate.get("bear_evidence").and_then(Value::as_array) {
        if !evidence.is_empty() {
            for (i, evidence) in evidence.iter().take(3).enumerate() {
                let text = evidence
                    .as_str()
                    .or_else(|| evidence.get("point").and_then(Value::as_str))
                    .unwrap_or("(no description)");
                section.push_str(&format!("{}. {}\n", i + 1, text));
            }
            let quality = collect_evidence_quality(debate, "bear");
            if !quality.is_empty() {
                section.push_str("\n\n**Source Quality:**\n");
                section.push_str(&quality);
            }
            return section;
        }
    }

    // Extract from debate turns whose role contains "bear".
    let evidence = extract_debate_evidence(debate, "bear");
    if evidence.is_empty() {
        section.push_str("- No bear evidence recorded.\n");
    } else {
        for (i, text) in evidence.iter().take(3).enumerate() {
            section.push_str(&format!("{}. {}\n", i + 1, text));
        }
    }
    let quality = collect_evidence_quality(debate, "bear");
    if !quality.is_empty() {
        section.push_str("\n\n**Source Quality:**\n");
        section.push_str(&quality);
    }
    section
}

/// Pull concise evidence strings from `debate_state_artifact.debate_turns`
/// filtered by role side ("bull" or "bear"). Each turn's `artifact.report`
/// (or `per_ticker[].key_evidence`) is mined for text.
fn extract_debate_evidence(debate: &Value, side: &str) -> Vec<String> {
    let mut evidence: Vec<String> = Vec::new();
    let turns = debate.get("debate_turns").and_then(Value::as_array);
    if let Some(turns) = turns {
        for turn in turns {
            let role = turn.get("role").and_then(Value::as_str).unwrap_or("");
            if !role.to_ascii_lowercase().contains(side) {
                continue;
            }
            let artifact = turn.get("artifact").unwrap_or(&Value::Null);
            // Prefer key_evidence arrays on per-ticker payloads.
            if let Some(per_ticker) = artifact.get("per_ticker").and_then(Value::as_object) {
                for data in per_ticker.values() {
                    if let Some(items) = data.get("key_evidence").and_then(Value::as_array) {
                        for item in items {
                            if let Some(text) = item.as_str() {
                                evidence.push(text.to_string());
                            }
                        }
                    }
                }
            }
            // Fall back to the report prose (first non-empty line).
            if evidence.is_empty() {
                if let Some(report) = artifact.get("report").and_then(Value::as_str) {
                    let first_line = report
                        .lines()
                        .map(str::trim)
                        .find(|line| !line.is_empty())
                        .unwrap_or("");
                    if !first_line.is_empty() {
                        evidence.push(first_line.to_string());
                    }
                }
            }
            if evidence.len() >= 3 {
                break;
            }
        }
    }
    evidence
}

/// Collect per-evidence source-quality and ticker-level consensus-risk
/// metadata for one debate side ("bull" / "bear"). Returns a Markdown-ready
/// string (empty when no structured quality data is present). Defensive:
/// missing fields are skipped, plain-string evidence is ignored.
fn collect_evidence_quality(debate: &Value, side: &str) -> String {
    let mut lines: Vec<String> = Vec::new();
    if let Some(turns) = debate.get("debate_turns").and_then(Value::as_array) {
        for turn in turns {
            let role = turn.get("role").and_then(Value::as_str).unwrap_or("");
            if !role.to_ascii_lowercase().contains(side) {
                continue;
            }
            let artifact = turn.get("artifact").unwrap_or(&Value::Null);
            if let Some(per_ticker) = artifact.get("per_ticker").and_then(Value::as_object) {
                for data in per_ticker.values() {
                    for field in ["echo_chamber_risk", "crowded_consensus_risk"] {
                        if let Some(value) = data.get(field).and_then(Value::as_str) {
                            if !value.trim().is_empty() {
                                lines.push(format!("- {}: {}", field.replace('_', " "), value));
                            }
                        }
                    }
                    if let Some(items) = data.get("key_evidence").and_then(Value::as_array) {
                        for item in items {
                            if let Some(obj) = item.as_object() {
                                let tier =
                                    obj.get("source_tier").and_then(Value::as_str).unwrap_or("");
                                let first = obj
                                    .get("first_source")
                                    .and_then(Value::as_str)
                                    .unwrap_or("");
                                let mut bits: Vec<String> = Vec::new();
                                if !tier.is_empty() {
                                    bits.push(format!("source tier: {tier}"));
                                }
                                if !first.is_empty() {
                                    bits.push(format!("first source: {first}"));
                                }
                                if let Some(true) =
                                    obj.get("is_derivative_repost").and_then(Value::as_bool)
                                {
                                    bits.push("derivative repost".to_string());
                                }
                                if !bits.is_empty() {
                                    let claim =
                                        obj.get("claim").and_then(Value::as_str).unwrap_or("");
                                    lines.push(format!("- {claim} ({})", bits.join(", ")));
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    lines.join("\n")
}

fn risk_field_str<'a>(rc: &'a Value, field: &str) -> Option<&'a str> {
    rc.get(field)
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
}

fn risk_field_pct(rc: &Value, field: &str) -> Option<String> {
    rc.get(field)
        .and_then(Value::as_f64)
        .filter(|value| *value != 0.0)
        .map(|value| format!("{:.0}%", value * 100.0))
}

fn risk_assessment(risk_state: &Value, allocation: &Value) -> String {
    let vix_regime = allocation
        .get("vix_regime")
        .and_then(Value::as_str)
        .unwrap_or("N/A");

    // History entries store the artifact under `.artifact` (see contract.rs).
    let history = risk_state
        .get("history")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();

    // `recommended_adjustment` lives at the top level in some flows and inside
    // the last history artifact in others — check both.
    let recommended = risk_state
        .get("recommended_adjustment")
        .and_then(Value::as_str)
        .or_else(|| {
            history
                .last()
                .and_then(|entry| entry.get("artifact").or(Some(entry)))
                .and_then(|artifact| artifact.get("recommended_adjustment"))
                .and_then(Value::as_str)
        })
        .unwrap_or("None");

    let mut section = format!(
        "## 5. Risk Assessment\n\n\
        **VIX Regime:** {vix_regime}\n\
        **Recommended Adjustment:** {recommended}\n\n\
        Key risks identified:\n"
    );

    let mut risks: Vec<String> = Vec::new();

    for entry in &history {
        let artifact = entry.get("artifact").unwrap_or(entry);
        // Prefer structured risk lists when available.
        let mut found_structured = false;
        if let Some(key_risks) = artifact.get("key_risks").and_then(Value::as_array) {
            for risk in key_risks {
                if let Some(text) = risk.as_str() {
                    risks.push(text.to_string());
                    found_structured = true;
                }
            }
        }
        if let Some(balanced) = artifact.get("balanced_view").and_then(Value::as_array) {
            for view in balanced {
                if let Some(text) = view.as_str() {
                    risks.push(text.to_string());
                    found_structured = true;
                }
            }
        }
        // Fall back to the RiskConstraints `argument` prose for this entry.
        if !found_structured {
            if let Some(argument) = artifact.get("argument").and_then(Value::as_str) {
                if !argument.trim().is_empty() {
                    risks.push(argument.to_string());
                }
            }
        }
    }

    // Direct RiskConstraints (no history wrapper).
    if risks.is_empty() {
        if let Some(argument) = risk_state.get("argument").and_then(Value::as_str) {
            if !argument.trim().is_empty() {
                risks.push(argument.to_string());
            }
        }
    }
    // FinalValidation.risk_controls is a Vec<String> of risk controls.
    if risks.is_empty() {
        if let Some(controls) = risk_state.get("risk_controls").and_then(Value::as_array) {
            for control in controls {
                if let Some(text) = control.as_str() {
                    risks.push(text.to_string());
                }
            }
        }
    }

    if risks.is_empty() {
        section.push_str("- No specific risks identified.\n");
    } else {
        for risk in risks.iter().take(5) {
            section.push_str(&format!("- {}\n", risk));
        }
    }

    // Surface structured RiskConstraints fields when present. These live at
    // the top level of `risk_debate_state` or inside the last history
    // artifact in some flows. Missing fields are skipped.
    let rc = history
        .last()
        .map(|entry| entry.get("artifact").unwrap_or(entry))
        .unwrap_or(risk_state);
    let structured: Vec<String> = vec![
        risk_field_str(rc, "stop_type").map(|value| format!("- **Stop Type:** {value}")),
        risk_field_pct(rc, "max_drawdown_pct").map(|value| format!("- **Max Drawdown:** {value}")),
        risk_field_pct(rc, "position_cap_pct").map(|value| format!("- **Position Cap:** {value}")),
        risk_field_str(rc, "rebalance_trigger")
            .map(|value| format!("- **Rebalance Trigger:** {value}")),
        risk_field_str(rc, "risk_off_trigger")
            .map(|value| format!("- **Risk-Off Trigger:** {value}")),
        risk_field_str(rc, "review_window").map(|value| format!("- **Review Window:** {value}")),
        risk_field_str(rc, "cash_hedge_recommendation")
            .map(|value| format!("- **Cash Hedge:** {value}")),
        risk_field_pct(rc, "constraint_confidence")
            .map(|value| format!("- **Constraint Confidence:** {value}")),
    ]
    .into_iter()
    .flatten()
    .collect();
    if !structured.is_empty() {
        section.push_str("\n**Structured Risk Constraints:**\n");
        for line in structured {
            section.push_str(&format!("{line}\n"));
        }
    }
    section
}

fn trade_plan(trader: &Value, final_decision: &Value) -> String {
    let action = trader
        .get("action")
        .and_then(Value::as_str)
        .or_else(|| final_decision.get("rating").and_then(Value::as_str))
        .unwrap_or("N/A");
    let position_size = trader
        .get("position_size")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    // TradeIntent exposes `entry_price` / `stop_loss`; accept `entry` / `stop`
    // aliases for forward compatibility with the plan template.
    let entry = trader
        .get("entry_price")
        .and_then(Value::as_str)
        .or_else(|| trader.get("entry").and_then(Value::as_str))
        .unwrap_or("N/A");
    let stop = trader
        .get("stop_loss")
        .and_then(Value::as_str)
        .or_else(|| trader.get("stop").and_then(Value::as_str))
        .unwrap_or("N/A");
    let horizon = final_decision
        .get("horizon")
        .and_then(Value::as_str)
        .unwrap_or("N/A");

    format!(
        "## 6. Trade Plan\n\n\
        | Parameter | Value |\n|-----------|-------|\n\
        | Action | {action} |\n\
        | Position Size | {position_size} |\n\
        | Entry | {entry} |\n\
        | Stop Loss | {stop} |\n\
        | Horizon | {horizon} |\n"
    )
}

fn portfolio_allocation(allocation: &Value) -> String {
    let mut section = String::from("## 7. Portfolio Allocation\n\n");
    let weights = allocation.get("weights").and_then(Value::as_object);

    if let Some(weights) = weights {
        if weights.is_empty() {
            section.push_str("No allocation data available.\n");
        } else {
            section.push_str("| Asset | Weight | Rationale |\n|-------|--------|-----------|\n");
            for (asset, data) in weights {
                let weight = data.get("weight").and_then(Value::as_f64).unwrap_or(0.0);
                let rationale = data.get("rationale").and_then(Value::as_str).unwrap_or("");
                section.push_str(&format!(
                    "| {} | {:.1}% | {} |\n",
                    asset,
                    weight * 100.0,
                    rationale
                ));
            }
        }
    } else {
        section.push_str("No allocation data available.\n");
    }

    let total = allocation.get("total_equity_exposure");
    let total_str = match total {
        Some(Value::Number(n)) => format_pct(&Value::Number(n.clone())),
        Some(value) => format_pct(value),
        None => "N/A".to_string(),
    };
    let corr = allocation
        .get("correlation_note")
        .and_then(Value::as_str)
        .unwrap_or("");
    let summary = allocation
        .get("summary")
        .and_then(Value::as_str)
        .unwrap_or("");

    section.push_str(&format!(
        "\n**Total Equity Exposure:** {}\n**Correlation Note:** {}\n\n{}\n",
        total_str, corr, summary
    ));
    section
}

fn confidence_and_limitations(research: &Value) -> String {
    let mut section = String::from("## 8. Confidence & Limitations\n\n");

    let data_gaps = research
        .get("data_gaps")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let validation_triggers = research
        .get("validation_triggers")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();

    section.push_str("**Data Gaps:**\n");
    if data_gaps.is_empty() {
        section.push_str("- None identified.\n");
    } else {
        for gap in &data_gaps {
            if let Some(text) = gap.as_str() {
                section.push_str(&format!("- {}\n", text));
            }
        }
    }

    section.push_str("\n**Validation Triggers:**\n");
    if validation_triggers.is_empty() {
        section.push_str("- None identified.\n");
    } else {
        for trigger in &validation_triggers {
            if let Some(text) = trigger.as_str() {
                section.push_str(&format!("- {}\n", text));
            }
        }
    }
    section
}

fn next_steps(research: &Value) -> String {
    let mut section =
        String::from("## 9. Next Steps\n\nObservation checklist from research manager:\n");
    let plan = research.get("plan").and_then(Value::as_str).or_else(|| {
        research
            .get("observation_checklist")
            .and_then(Value::as_str)
    });

    if let Some(plan_text) = plan {
        // Split plan text into bullet points if it contains newlines or semicolons.
        let items: Vec<&str> = plan_text
            .split('\n')
            .flat_map(|s| s.split(';'))
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .collect();
        if items.is_empty() {
            section.push_str(&format!("- {}\n", plan_text));
        } else {
            for item in items.iter().take(10) {
                section.push_str(&format!("- {}\n", item));
            }
        }
    } else {
        section.push_str("- No observation checklist provided.\n");
    }
    section
}

/// Format a probability/exposure value as a percentage.
///
/// Values in the `[0.0, 1.0]` range are multiplied by 100; values above `1.0`
/// are treated as already being on a 0-100 scale. String values are passed
/// through unchanged.
fn format_pct(value: &Value) -> String {
    match value {
        Value::Number(n) => {
            let f = n.as_f64().unwrap_or(0.0);
            if f > 1.0 {
                format!("{:.0}%", f)
            } else {
                format!("{:.0}%", f * 100.0)
            }
        }
        Value::String(s) => s.to_string(),
        _ => "N/A".to_string(),
    }
}

/// Convert a Markdown report into a standalone, styled HTML document.
///
/// Uses `pulldown-cmark` for spec-compliant CommonMark parsing and wraps the
/// fragment in a full `<!doctype html>` document with inline CSS so it renders
/// correctly in email clients.
pub fn report_to_html(markdown: &str) -> String {
    // Enable table and strikethrough extensions so the Trade Plan and Portfolio
    // Allocation Markdown tables render as proper <table> elements.
    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_STRIKETHROUGH);
    let parser = Parser::new_ext(markdown, options);
    let mut body = String::new();
    html::push_html(&mut body, parser);

    let title = markdown
        .lines()
        .find_map(|line| line.strip_prefix("# ").map(str::trim))
        .unwrap_or("Strategy Report");

    format!(
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>{title}</title>\
        <style>{css}</style></head><body>{body}</body></html>",
        title = encode_text(title),
        css = REPORT_CSS,
        body = body
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn full_state() -> Value {
        json!({
            "ticker": "TQQQ",
            "current_date": "2026-07-06",
            "research_plan": {
                "rating": "Buy",
                "long_probability": 0.72,
                "short_probability": 0.28,
                "probability_rationale": "Momentum and breadth support a long position.",
                "dominant_driver": "Earnings momentum",
                "why_now": "VIX regime shifted to normal.",
                "plan": "Watch 20DMA hold; add on pullback to 45.\nConfirm volume expansion.\nReview Fed minutes.",
                "data_gaps": ["Intraday flow data missing", "Options skew stale"],
                "validation_triggers": ["Close below 20DMA", "VIX > 25"]
            },
            "trader_investment_plan": {
                "action": "Buy",
                "entry_price": "$45.00",
                "stop_loss": "$42.50",
                "position_size": "30%-50%",
                "rationale": "Risk-on with tight stop."
            },
            "risk_debate_state": {
                "history": [
                    {
                        "artifact": {
                            "stance": "conservative",
                            "argument": "Position sizing must respect VIX spike risk.",
                            "recommended_adjustment": "Cap equity exposure at 60%."
                        }
                    }
                ],
                "recommended_adjustment": "Cap equity exposure at 60%."
            },
            "final_trade_decision": {
                "rating": "Buy",
                "horizon": "1-5 trading days",
                "investment_thesis": "Bullish momentum with controlled risk.",
                "execution_summary": "Buy 30%-50% with stop at 42.50.",
                "risk_controls": ["Stop at 42.50", "Max 60% equity exposure"]
            },
            "portfolio_allocation": {
                "weights": {
                    "TQQQ": { "weight": 0.45, "rationale": "Primary long exposure" },
                    "cash_hedge": { "weight": 0.55, "rationale": "VIX-normal cash buffer" }
                },
                "total_equity_exposure": 0.45,
                "vix_regime": "normal",
                "correlation_note": "Low cross-asset correlation.",
                "summary": "Balanced long bias with cash hedge."
            },
            "debate_state_artifact": {
                "debate_turns": [
                    {
                        "role": "researcher.bull.initial",
                        "artifact": {
                            "report": "Bullish: earnings beat and guidance raised.",
                            "per_ticker": {
                                "TQQQ": { "key_evidence": ["Earnings beat", "Guidance raised", "20DMA holding"] }
                            }
                        }
                    },
                    {
                        "role": "researcher.bear.initial",
                        "artifact": {
                            "report": "Bearish: RSI overbought and breadth narrowing.",
                            "per_ticker": {
                                "TQQQ": { "key_evidence": ["RSI overbought", "Breadth narrowing"] }
                            }
                        }
                    }
                ]
            }
        })
    }

    #[test]
    fn generates_all_nine_sections() {
        let report = build_human_readable_report(&full_state());
        for n in 1..=9 {
            assert!(
                report.contains(&format!("## {}. ", n)),
                "report missing section {}: {}",
                n,
                report
            );
        }
    }

    #[test]
    fn executive_summary_contains_rating_and_action() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("**Buy**"));
        assert!(report.contains("**Recommended Action:** Buy"));
        assert!(report.contains("72%"));
        assert!(report.contains("28%"));
    }

    #[test]
    fn bull_case_extracts_evidence_from_debate_turns() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("## 3. Bull Case"));
        assert!(report.contains("Earnings beat"));
    }

    #[test]
    fn bear_case_extracts_evidence_from_debate_turns() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("## 4. Bear Case"));
        assert!(report.contains("RSI overbought"));
    }

    #[test]
    fn trade_plan_uses_entry_price_and_stop_loss() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("| Entry | $45.00 |"));
        assert!(report.contains("| Stop Loss | $42.50 |"));
        assert!(report.contains("| Horizon | 1-5 trading days |"));
    }

    #[test]
    fn portfolio_allocation_renders_table() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("| TQQQ | 45.0% | Primary long exposure |"));
        assert!(report.contains("**Total Equity Exposure:** 45%"));
    }

    #[test]
    fn empty_state_does_not_crash() {
        let report = build_human_readable_report(&json!({}));
        assert!(report.contains("# N/A Strategy Report"));
        assert!(report.contains("## 1. Executive Summary"));
        assert!(report.contains("N/A"));
        assert!(report.contains("- No bull evidence recorded."));
        assert!(report.contains("- No bear evidence recorded."));
        assert!(report.contains("No allocation data available."));
    }

    #[test]
    fn partial_state_with_only_research_plan() {
        let state = json!({
            "ticker": "QQQ",
            "current_date": "2026-07-06",
            "research_plan": {
                "rating": "Hold",
                "long_probability": 0.5,
                "short_probability": 0.5,
                "confidence_basis": "data_insufficient",
                "hold_reason": "evidence_insufficient",
                "probability_rationale": "Neutral.",
                "plan": "Monitor."
            }
        });
        let report = build_human_readable_report(&state);
        assert!(report.contains("## 1. Executive Summary"));
        assert!(report.contains("## 9. Next Steps"));
        assert!(report.contains("- Monitor."));
        assert!(report.contains("- No bull evidence recorded."));
        assert!(report.contains("- No specific risks identified."));
        assert!(report.contains("Confidence basis: data_insufficient"));
        assert!(report.contains("Hold reason: evidence_insufficient"));
    }

    #[test]
    fn report_to_html_produces_well_formed_document() {
        let markdown = build_human_readable_report(&full_state());
        let html = report_to_html(&markdown);
        assert!(html.starts_with("<!doctype html>"));
        assert!(html.contains("<html>"));
        assert!(html.contains("<head>"));
        assert!(html.contains("<title>"));
        assert!(html.contains("<body>"));
        assert!(html.contains("</body></html>"));
        assert!(html.contains("<style>"));
    }

    #[test]
    fn report_to_html_renders_tables() {
        let markdown = build_human_readable_report(&full_state());
        let html = report_to_html(&markdown);
        assert!(html.contains("<table>"));
        assert!(html.contains("<th>"));
        assert!(html.contains("<td>"));
    }

    #[test]
    fn format_pct_handles_fraction_and_percent() {
        assert_eq!(format_pct(&json!(0.72)), "72%");
        assert_eq!(format_pct(&json!(72.0)), "72%");
        assert_eq!(format_pct(&json!("72%")), "72%");
        assert_eq!(format_pct(&json!(0.0)), "0%");
    }

    #[test]
    fn report_preserves_backward_compat_final_summary_format() {
        // The report should be valid Markdown with horizontal rules between sections.
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("---"));
        assert!(report.contains("*Generated by Akzio Signal Intelligence"));
    }

    #[test]
    fn bull_evidence_direct_field_is_preferred() {
        let state = json!({
            "ticker": "TQQQ",
            "current_date": "2026-07-06",
            "debate_state_artifact": {
                "bull_evidence": ["Direct bull point A", "Direct bull point B"],
                "bear_evidence": ["Direct bear point A"]
            }
        });
        let report = build_human_readable_report(&state);
        assert!(report.contains("Direct bull point A"));
        assert!(report.contains("Direct bear point A"));
    }
}
