//! Human-readable report builder.
//!
//! Converts the structured state artifacts (research_plan, trader_investment_plan,
//! risk_debate_state, final_trade_decision, portfolio_allocation, debate_state_artifact)
//! into a 9-section Markdown report and a styled HTML document.
//!
//! See `plan/P2-07-human-readable-report.md` for the full specification.

use chrono::Local;
use serde_json::{Map, Value};
use std::collections::BTreeSet;

#[path = "html.rs"]
mod html;

pub use html::report_to_html;

const REPORT_PROJECTION_FIELDS: &[&str] = &[
    "current_date",
    "ticker",
    "tickers",
    "investable_assets",
    "mock",
    "debug",
    "storage_namespace",
    "research_plan",
    "trader_investment_plan",
    "risk_debate_state",
    "final_trade_decision",
    "portfolio_allocation",
    "debate_state_artifact",
];

/// The compacted Phase 8 Index keeps this bounded, presentation-safe
/// projection so a report can be rendered after transient run state is gone.
pub(crate) fn report_projection(state: &Value) -> Value {
    let mut projection = Map::new();
    for field in REPORT_PROJECTION_FIELDS {
        projection.insert(
            (*field).to_owned(),
            state.get(*field).cloned().unwrap_or(Value::Null),
        );
    }
    Value::Object(projection)
}

/// A report is only eligible for external delivery when every canonical
/// phase-owned section is available, rather than when a state file merely
/// happens to exist.
pub(crate) fn has_complete_report_projection(state: &Value) -> bool {
    [
        "/research_plan/per_ticker",
        "/trader_investment_plan/per_ticker",
        "/final_trade_decision/per_asset",
        "/portfolio_allocation/weights",
        "/risk_debate_state",
        "/debate_state_artifact",
    ]
    .into_iter()
    .all(|pointer| {
        state
            .pointer(pointer)
            .and_then(Value::as_object)
            .is_some_and(|fields| !fields.is_empty())
    })
}

/// Build a structured human-readable Markdown report from state artifacts.
///
/// Every section degrades gracefully when its source artifact is missing —
/// placeholders ("N/A", "No data available") are emitted instead of panicking.
pub fn build_human_readable_report(state: &Value) -> String {
    let date = state
        .get("current_date")
        .and_then(Value::as_str)
        .or_else(|| state.get("date").and_then(Value::as_str))
        .unwrap_or("N/A");
    let ticker = state
        .get("ticker")
        .and_then(Value::as_str)
        .or_else(|| {
            state
                .get("tickers")
                .and_then(Value::as_array)
                .and_then(|items| items.first())
                .and_then(Value::as_str)
        })
        .unwrap_or("N/A");
    let timestamp = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();

    let primary_asset = primary_report_asset(state);
    let research = report_asset_view(
        state.get("research_plan").unwrap_or(&Value::Null),
        "per_ticker",
        primary_asset.as_deref(),
    );
    let trader = report_asset_view(
        state.get("trader_investment_plan").unwrap_or(&Value::Null),
        "per_ticker",
        primary_asset.as_deref(),
    );
    let final_decision = report_asset_view(
        state.get("final_trade_decision").unwrap_or(&Value::Null),
        "per_asset",
        primary_asset.as_deref(),
    );
    let allocation = state.get("portfolio_allocation").unwrap_or(&Value::Null);
    let risk_state = state.get("risk_debate_state").unwrap_or(&Value::Null);
    let debate = state.get("debate_state_artifact").unwrap_or(&Value::Null);

    let mut report = String::new();
    report.push_str(&format!("# {} Strategy Report — {}\n\n", ticker, date));

    // Section 1: Executive Summary
    report.push_str(&executive_summary(research, trader, final_decision));
    report.push_str("\n---\n\n");

    // Section 2: Investment Thesis
    report.push_str(&investment_thesis(research, final_decision));
    report.push_str("\n---\n\n");

    // Section 3: Bull Case
    report.push_str(&bull_case(debate));
    report.push_str("\n---\n\n");

    // Section 4: Bear Case
    report.push_str(&bear_case(debate));
    report.push_str("\n---\n\n");

    // Section 5: Risk Assessment
    report.push_str(&risk_assessment(risk_state, allocation));
    report.push_str("\n---\n\n");

    // Section 6: Trade Plan
    report.push_str(&trade_plan(trader, final_decision));
    report.push_str("\n---\n\n");

    // Section 7: Portfolio Allocation
    report.push_str(&portfolio_allocation(allocation));
    report.push_str("\n---\n\n");

    // Section 8: Confidence & Limitations
    report.push_str(&confidence_and_limitations(research));
    report.push_str("\n---\n\n");

    // Section 9: Next Steps
    report.push_str(&next_steps(research));
    report.push_str(&format!(
        "\n---\n*Generated by Akzio Signal Intelligence | {}*\n",
        timestamp
    ));

    report
}

fn primary_report_asset(state: &Value) -> Option<String> {
    for field in ["investable_assets", "tickers"] {
        for candidate in state
            .get(field)
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
        {
            if report_asset_exists(state, candidate) {
                return Some(candidate.to_owned());
            }
        }
    }
    [
        ("research_plan", "per_ticker"),
        ("trader_investment_plan", "per_ticker"),
        ("final_trade_decision", "per_asset"),
    ]
    .into_iter()
    .find_map(|(field, collection)| {
        state
            .get(field)
            .and_then(|value| value.get(collection))
            .and_then(Value::as_object)
            .and_then(|items| items.keys().next())
            .cloned()
    })
}

fn report_asset_exists(state: &Value, asset: &str) -> bool {
    [
        ("research_plan", "per_ticker"),
        ("trader_investment_plan", "per_ticker"),
        ("final_trade_decision", "per_asset"),
    ]
    .into_iter()
    .any(|(field, collection)| {
        state
            .get(field)
            .and_then(|value| value.get(collection))
            .and_then(Value::as_object)
            .is_some_and(|items| items.contains_key(asset))
    })
}

fn report_asset_view<'a>(root: &'a Value, collection: &str, asset: Option<&str>) -> &'a Value {
    let Some(asset) = asset else {
        return root;
    };
    root.get(collection)
        .and_then(Value::as_object)
        .and_then(|items| items.get(asset))
        .unwrap_or(root)
}

fn executive_summary(research: &Value, trader: &Value, final_decision: &Value) -> String {
    let rating = research
        .get("rating")
        .and_then(Value::as_str)
        .or_else(|| final_decision.get("rating").and_then(Value::as_str))
        .or_else(|| final_decision.get("direction").and_then(Value::as_str))
        .unwrap_or("N/A");
    let long_prob = research
        .get("long_probability")
        .map(format_pct)
        .unwrap_or_else(|| "N/A".to_string());
    let short_prob = research
        .get("short_probability")
        .map(format_pct)
        .unwrap_or_else(|| "N/A".to_string());
    let rationale = research
        .get("probability_rationale")
        .and_then(Value::as_str)
        .unwrap_or("");
    let dominant_driver = research
        .get("dominant_driver")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    let why_now = research
        .get("why_now")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    let action = trader
        .get("action")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    let confidence_basis = research
        .get("confidence_basis")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty());
    let hold_reason = research
        .get("hold_reason")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty());
    let mut basis_summary = String::new();
    if let Some(value) = confidence_basis {
        basis_summary.push_str(&format!("Confidence basis: {value}\n"));
    }
    if let Some(value) = hold_reason {
        basis_summary.push_str(&format!("Hold reason: {value}\n"));
    }

    format!(
        "## 1. Executive Summary\n\n\
        Current rating: **{rating}** (long: {long_prob}, short: {short_prob}).\n\
        {basis_summary}\
        {rationale}\n\n\
        **Dominant Driver:** {dominant_driver}\n\
        **Why Now:** {why_now}\n\n\
        **Recommended Action:** {action}\n"
    )
}

fn investment_thesis(research: &Value, final_decision: &Value) -> String {
    let rating = final_decision
        .get("rating")
        .and_then(Value::as_str)
        .or_else(|| final_decision.get("direction").and_then(Value::as_str))
        .or_else(|| research.get("rating").and_then(Value::as_str))
        .unwrap_or("N/A");
    let horizon = final_decision
        .get("horizon")
        .and_then(Value::as_str)
        .unwrap_or("N/A");
    let long_prob = research
        .get("long_probability")
        .map(format_pct)
        .unwrap_or_else(|| "N/A".to_string());
    let short_prob = research
        .get("short_probability")
        .map(format_pct)
        .unwrap_or_else(|| "N/A".to_string());
    let rationale = research
        .get("probability_rationale")
        .and_then(Value::as_str)
        .unwrap_or("");
    let thesis = final_decision
        .get("investment_thesis")
        .and_then(Value::as_str)
        .filter(|text| !text.trim().is_empty())
        .unwrap_or("");

    let mut section = format!(
        "## 2. Investment Thesis\n\n\
        Rating: **{rating}** | Horizon: {horizon}\n\
        Probability: Long {long_prob} / Short {short_prob}\n\n\
        {rationale}\n"
    );
    if !thesis.is_empty() {
        section.push_str(&format!("\n{thesis}\n"));
    }
    section
}

fn bull_case(debate: &Value) -> String {
    let mut section = String::from("## 3. Bull Case\n\nTop bull evidence from debate:\n");

    // Forward-compatible direct field.
    if let Some(evidence) = debate.get("bull_evidence").and_then(Value::as_array) {
        if !evidence.is_empty() {
            for (i, evidence) in evidence.iter().take(3).enumerate() {
                let text = evidence
                    .as_str()
                    .or_else(|| evidence.get("point").and_then(Value::as_str))
                    .unwrap_or("(no description)");
                section.push_str(&format!("{}. {}\n", i + 1, text));
            }
            return section;
        }
    }

    // Extract from debate turns whose role contains "bull".
    let evidence = extract_debate_evidence(debate, "bull");
    if evidence.is_empty() {
        section.push_str("- No bull evidence recorded.\n");
    } else {
        for (i, text) in evidence.iter().take(3).enumerate() {
            section.push_str(&format!("{}. {}\n", i + 1, text));
        }
    }
    let quality = collect_evidence_quality(debate, "bull");
    if !quality.is_empty() {
        section.push_str("\n\n**Source Quality:**\n");
        section.push_str(&quality);
    }
    section
}

fn bear_case(debate: &Value) -> String {
    let mut section = String::from("## 4. Bear Case\n\nTop bear evidence from debate:\n");

    // Forward-compatible direct field.
    if let Some(evidence) = debate.get("bear_evidence").and_then(Value::as_array) {
        if !evidence.is_empty() {
            for (i, evidence) in evidence.iter().take(3).enumerate() {
                let text = evidence
                    .as_str()
                    .or_else(|| evidence.get("point").and_then(Value::as_str))
                    .unwrap_or("(no description)");
                section.push_str(&format!("{}. {}\n", i + 1, text));
            }
            let quality = collect_evidence_quality(debate, "bear");
            if !quality.is_empty() {
                section.push_str("\n\n**Source Quality:**\n");
                section.push_str(&quality);
            }
            return section;
        }
    }

    // Extract from debate turns whose role contains "bear".
    let evidence = extract_debate_evidence(debate, "bear");
    if evidence.is_empty() {
        section.push_str("- No bear evidence recorded.\n");
    } else {
        for (i, text) in evidence.iter().take(3).enumerate() {
            section.push_str(&format!("{}. {}\n", i + 1, text));
        }
    }
    let quality = collect_evidence_quality(debate, "bear");
    if !quality.is_empty() {
        section.push_str("\n\n**Source Quality:**\n");
        section.push_str(&quality);
    }
    section
}

/// Pull concise claims from finalized Phase 2 turn payloads filtered by side.
fn extract_debate_evidence(debate: &Value, side: &str) -> Vec<String> {
    let mut evidence = Vec::new();
    for (role, payload) in debate_entries(debate) {
        if !role.to_ascii_lowercase().contains(side) {
            continue;
        }
        for item in payload
            .get("claims")
            .or_else(|| payload.get("responses"))
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            if let Some(text) = item
                .get("claim")
                .or_else(|| item.get("response"))
                .and_then(Value::as_str)
                .filter(|text| !text.trim().is_empty())
            {
                push_unique(&mut evidence, text);
            }
        }
        if let Some(report) = payload
            .get("report")
            .and_then(Value::as_str)
            .filter(|text| !text.trim().is_empty())
        {
            push_unique(&mut evidence, report);
        }
        if evidence.len() >= 3 {
            break;
        }
    }
    evidence
}

/// Collect source reference provenance for one debate side.
fn collect_evidence_quality(debate: &Value, side: &str) -> String {
    let mut references = BTreeSet::new();
    for (role, payload) in debate_entries(debate) {
        if !role.to_ascii_lowercase().contains(side) {
            continue;
        }
        collect_evidence_refs(payload, &mut references);
        for item in payload
            .get("claims")
            .or_else(|| payload.get("responses"))
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            collect_evidence_refs(item, &mut references);
        }
    }
    references
        .into_iter()
        .map(|reference| format!("- evidence reference: {reference}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn debate_entries(debate: &Value) -> Vec<(&str, &Value)> {
    let mut entries = Vec::new();
    for turn in debate
        .get("debate_turns")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        if let Some(role) = turn.get("role").and_then(Value::as_str) {
            entries.push((role, artifact_payload(turn)));
        }
    }
    for controller in debate
        .pointer("/final_reducer/authoritative_fields/controllers")
        .and_then(Value::as_object)
        .into_iter()
        .flat_map(|controllers| controllers.values())
    {
        for node in controller
            .get("nodes")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            if let Some(role) = node.get("from").and_then(Value::as_str) {
                entries.push((role, artifact_payload(node)));
            }
        }
    }
    entries
}

fn artifact_payload(value: &Value) -> &Value {
    let artifact = value.get("artifact").unwrap_or(value);
    artifact.get("payload").unwrap_or(artifact)
}

fn collect_evidence_refs(value: &Value, output: &mut BTreeSet<String>) {
    for reference in value
        .get("evidence_refs")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .filter(|reference| !reference.trim().is_empty())
    {
        output.insert(reference.to_owned());
    }
}

fn push_unique(output: &mut Vec<String>, value: &str) {
    if !output.iter().any(|existing| existing == value) {
        output.push(value.to_owned());
    }
}

fn risk_field_str<'a>(rc: &'a Value, field: &str) -> Option<&'a str> {
    rc.get(field)
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
}

fn risk_field_pct(rc: &Value, field: &str) -> Option<String> {
    rc.get(field)
        .and_then(Value::as_f64)
        .filter(|value| *value != 0.0)
        .map(|value| format!("{:.0}%", value * 100.0))
}

fn risk_assessment(risk_state: &Value, allocation: &Value) -> String {
    let vix_regime = allocation
        .get("vix_regime")
        .and_then(Value::as_str)
        .unwrap_or("N/A");

    // History entries store the artifact under `.artifact` (see contract.rs).
    let history = risk_state
        .get("history")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();

    // `recommended_adjustment` lives at the top level in some flows and inside
    // the last history artifact in others — check both.
    let recommended = risk_state
        .get("recommended_adjustment")
        .and_then(Value::as_str)
        .or_else(|| {
            history
                .last()
                .and_then(|entry| artifact_payload(entry).get("recommended_adjustment"))
                .and_then(Value::as_str)
        })
        .unwrap_or("None");

    let mut section = format!(
        "## 5. Risk Assessment\n\n\
        **VIX Regime:** {vix_regime}\n\
        **Recommended Adjustment:** {recommended}\n\n\
        Key risks identified:\n"
    );

    let mut risks: Vec<String> = Vec::new();

    for entry in &history {
        let artifact = artifact_payload(entry);
        // Prefer structured risk lists when available.
        let mut found_structured = false;
        if let Some(key_risks) = artifact.get("key_risks").and_then(Value::as_array) {
            for risk in key_risks {
                if let Some(text) = risk.as_str() {
                    risks.push(text.to_string());
                    found_structured = true;
                }
            }
        }
        if let Some(balanced) = artifact.get("balanced_view").and_then(Value::as_array) {
            for view in balanced {
                if let Some(text) = view.as_str() {
                    risks.push(text.to_string());
                    found_structured = true;
                }
            }
        }
        // Fall back to the RiskConstraints `argument` prose for this entry.
        if !found_structured {
            if let Some(argument) = artifact.get("argument").and_then(Value::as_str) {
                if !argument.trim().is_empty() {
                    risks.push(argument.to_string());
                }
            }
        }
    }

    // Direct RiskConstraints (no history wrapper).
    if risks.is_empty() {
        if let Some(argument) = risk_state.get("argument").and_then(Value::as_str) {
            if !argument.trim().is_empty() {
                risks.push(argument.to_string());
            }
        }
    }
    if risks.is_empty() {
        section.push_str("- No specific risks identified.\n");
    } else {
        for risk in risks.iter().take(5) {
            section.push_str(&format!("- {}\n", risk));
        }
    }

    // Surface structured RiskConstraints fields when present. These live at
    // the top level of `risk_debate_state` or inside the last history
    // artifact in some flows. Missing fields are skipped.
    let rc = history.last().map(artifact_payload).unwrap_or(risk_state);
    let structured: Vec<String> = vec![
        risk_field_str(rc, "stop_type").map(|value| format!("- **Stop Type:** {value}")),
        risk_field_pct(rc, "max_drawdown_pct").map(|value| format!("- **Max Drawdown:** {value}")),
        risk_field_pct(rc, "position_cap_pct").map(|value| format!("- **Position Cap:** {value}")),
        risk_field_str(rc, "rebalance_trigger")
            .map(|value| format!("- **Rebalance Trigger:** {value}")),
        risk_field_str(rc, "risk_off_trigger")
            .map(|value| format!("- **Risk-Off Trigger:** {value}")),
        risk_field_str(rc, "review_window").map(|value| format!("- **Review Window:** {value}")),
        risk_field_str(rc, "cash_hedge_recommendation")
            .map(|value| format!("- **Cash Hedge:** {value}")),
        risk_field_pct(rc, "constraint_confidence")
            .map(|value| format!("- **Constraint Confidence:** {value}")),
    ]
    .into_iter()
    .flatten()
    .collect();
    if !structured.is_empty() {
        section.push_str("\n**Structured Risk Constraints:**\n");
        for line in structured {
            section.push_str(&format!("{line}\n"));
        }
    }
    section
}

fn trade_plan(trader: &Value, final_decision: &Value) -> String {
    let action = trader
        .get("action")
        .and_then(Value::as_str)
        .or_else(|| final_decision.get("direction").and_then(Value::as_str))
        .or_else(|| final_decision.get("rating").and_then(Value::as_str))
        .unwrap_or("N/A");
    let position_size = trader
        .get("position_size_pct_max")
        .and_then(Value::as_f64)
        .map(|value| format!("{:.0}%", value * 100.0))
        .unwrap_or_else(|| "N/A".to_string());
    let entry = scalar_display(trader.get("entry_price"));
    let stop = scalar_display(trader.get("stop_loss"));
    let horizon = final_decision
        .get("horizon")
        .and_then(Value::as_str)
        .unwrap_or("N/A");

    format!(
        "## 6. Trade Plan\n\n\
        | Parameter | Value |\n|-----------|-------|\n\
        | Action | {action} |\n\
        | Position Size | {position_size} |\n\
        | Entry | {entry} |\n\
        | Stop Loss | {stop} |\n\
        | Horizon | {horizon} |\n"
    )
}

fn scalar_display(value: Option<&Value>) -> String {
    match value {
        Some(Value::String(value)) if !value.trim().is_empty() => value.to_owned(),
        Some(Value::Number(value)) => value.to_string(),
        _ => "N/A".to_owned(),
    }
}

fn portfolio_allocation(allocation: &Value) -> String {
    let mut section = String::from("## 7. Portfolio Allocation\n\n");
    let weights = allocation.get("weights").and_then(Value::as_object);

    if let Some(weights) = weights {
        if weights.is_empty() {
            section.push_str("No allocation data available.\n");
        } else {
            section.push_str("| Asset | Weight | Rationale |\n|-------|--------|-----------|\n");
            for (asset, data) in weights {
                let weight = data.get("weight").and_then(Value::as_f64).unwrap_or(0.0);
                let rationale = data.get("rationale").and_then(Value::as_str).unwrap_or("");
                section.push_str(&format!(
                    "| {} | {:.1}% | {} |\n",
                    asset,
                    weight * 100.0,
                    rationale
                ));
            }
        }
    } else {
        section.push_str("No allocation data available.\n");
    }

    let total = allocation.get("total_equity_exposure");
    let total_str = match total {
        Some(Value::Number(n)) => format_pct(&Value::Number(n.clone())),
        Some(value) => format_pct(value),
        None => "N/A".to_string(),
    };
    let corr = allocation
        .get("correlation_note")
        .and_then(Value::as_str)
        .unwrap_or("");
    let summary = allocation
        .get("summary")
        .and_then(Value::as_str)
        .unwrap_or("");

    section.push_str(&format!(
        "\n**Total Equity Exposure:** {}\n**Correlation Note:** {}\n\n{}\n",
        total_str, corr, summary
    ));
    section
}

fn confidence_and_limitations(research: &Value) -> String {
    let mut section = String::from("## 8. Confidence & Limitations\n\n");

    let data_gaps = research
        .get("data_gaps")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let validation_triggers = research
        .get("validation_triggers")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();

    section.push_str("**Data Gaps:**\n");
    if data_gaps.is_empty() {
        section.push_str("- None identified.\n");
    } else {
        for gap in &data_gaps {
            if let Some(text) = gap.as_str() {
                section.push_str(&format!("- {}\n", text));
            }
        }
    }

    section.push_str("\n**Validation Triggers:**\n");
    if validation_triggers.is_empty() {
        section.push_str("- None identified.\n");
    } else {
        for trigger in &validation_triggers {
            if let Some(text) = trigger.as_str() {
                section.push_str(&format!("- {}\n", text));
            }
        }
    }
    section
}

fn next_steps(research: &Value) -> String {
    let mut section =
        String::from("## 9. Next Steps\n\nObservation checklist from research manager:\n");
    let plan = research.get("plan").and_then(Value::as_str).or_else(|| {
        research
            .get("observation_checklist")
            .and_then(Value::as_str)
    });

    if let Some(plan_text) = plan {
        // Split plan text into bullet points if it contains newlines or semicolons.
        let items: Vec<&str> = plan_text
            .split('\n')
            .flat_map(|s| s.split(';'))
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .collect();
        if items.is_empty() {
            section.push_str(&format!("- {}\n", plan_text));
        } else {
            for item in items.iter().take(10) {
                section.push_str(&format!("- {}\n", item));
            }
        }
    } else {
        section.push_str("- No observation checklist provided.\n");
    }
    section
}

/// Format a probability/exposure value as a percentage.
///
/// Values in the `[0.0, 1.0]` range are multiplied by 100; values above `1.0`
/// are treated as already being on a 0-100 scale. String values are passed
/// through unchanged.
fn format_pct(value: &Value) -> String {
    match value {
        Value::Number(n) => {
            let f = n.as_f64().unwrap_or(0.0);
            if f > 1.0 {
                format!("{:.0}%", f)
            } else {
                format!("{:.0}%", f * 100.0)
            }
        }
        Value::String(s) => s.to_string(),
        _ => "N/A".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn full_state() -> Value {
        json!({
            "ticker": "TQQQ",
            "current_date": "2026-07-06",
            "research_plan": {
                "rating": "Buy",
                "long_probability": 0.72,
                "short_probability": 0.28,
                "probability_rationale": "Momentum and breadth support a long position.",
                "dominant_driver": "Earnings momentum",
                "why_now": "VIX regime shifted to normal.",
                "plan": "Watch 20DMA hold; add on pullback to 45.\nConfirm volume expansion.\nReview Fed minutes.",
                "data_gaps": ["Intraday flow data missing", "Options skew stale"],
                "validation_triggers": ["Close below 20DMA", "VIX > 25"]
            },
            "trader_investment_plan": {
                "action": "Buy",
                "entry_price": "$45.00",
                "stop_loss": "$42.50",
                "position_size_pct_max": 0.5,
                "rationale": "Risk-on with tight stop."
            },
            "risk_debate_state": {
                "history": [
                    {
                        "artifact": {
                            "stance": "conservative",
                            "argument": "Position sizing must respect VIX spike risk.",
                            "recommended_adjustment": "Cap equity exposure at 60%."
                        }
                    }
                ],
                "recommended_adjustment": "Cap equity exposure at 60%."
            },
            "final_trade_decision": {
                "rating": "Buy",
                "horizon": "1-5 trading days",
                "investment_thesis": "Bullish momentum with controlled risk.",
                "execution_summary": "Buy 30%-50% with stop at 42.50."
            },
            "portfolio_allocation": {
                "weights": {
                    "TQQQ": { "weight": 0.45, "rationale": "Primary long exposure" },
                    "cash_hedge": { "weight": 0.55, "rationale": "VIX-normal cash buffer" }
                },
                "total_equity_exposure": 0.45,
                "vix_regime": "normal",
                "correlation_note": "Low cross-asset correlation.",
                "summary": "Balanced long bias with cash hedge."
            },
            "debate_state_artifact": {
                "debate_turns": [
                    {
                        "role": "researcher.bull.initial",
                        "artifact": {
                            "payload": {"claims": [
                                {"claim": "Earnings beat", "evidence_refs": ["evidence:earnings"]},
                                {"claim": "Guidance raised", "evidence_refs": ["evidence:guidance"]}
                            ]}
                        }
                    },
                    {
                        "role": "researcher.bear.initial",
                        "artifact": {
                            "payload": {"claims": [
                                {"claim": "RSI overbought", "evidence_refs": ["evidence:rsi"]},
                                {"claim": "Breadth narrowing", "evidence_refs": ["evidence:breadth"]}
                            ]}
                        }
                    }
                ]
            }
        })
    }

    fn canonical_runtime_state() -> Value {
        json!({
            "ticker": "QQQ,SOXX,VIX",
            "current_date": "2026-07-06",
            "tickers": ["QQQ", "SOXX", "VIX"],
            "investable_assets": ["QQQ", "SOXX"],
            "research_plan": {"per_ticker": {
                "QQQ": {
                    "rating": "Buy",
                    "long_probability": 0.74,
                    "short_probability": 0.26,
                    "probability_rationale": "QQQ breadth improved.",
                    "dominant_driver": "QQQ momentum",
                    "why_now": "QQQ reclaimed support",
                    "plan": "Watch QQQ volume",
                    "data_gaps": [],
                    "validation_triggers": ["QQQ closes below support"]
                },
                "SOXX": {
                    "rating": "Hold",
                    "long_probability": 0.5,
                    "short_probability": 0.5
                }
            }},
            "trader_investment_plan": {"per_ticker": {
                "QQQ": {
                    "action": "Buy", "position_size_pct_max": 0.3,
                    "entry_price": 450.25, "stop_loss": 430.5
                },
                "SOXX": {"action": "Hold", "position_size_pct_max": 0.0}
            }},
            "risk_debate_state": {"history": [{"payload": {
                "argument": "Volatility can reverse the QQQ move.",
                "recommended_adjustment": "Keep a cash hedge."
            }}]},
            "final_trade_decision": {"per_asset": {
                "QQQ": {"direction": "Buy", "long_probability": 0.74, "short_probability": 0.26},
                "SOXX": {"direction": "Hold", "long_probability": 0.5, "short_probability": 0.5}
            }},
            "portfolio_allocation": {
                "weights": {
                    "QQQ": {"weight": 0.3, "rationale": "primary exposure"},
                    "SOXX": {"weight": 0.1, "rationale": "diversifier"},
                    "cash_hedge": {"weight": 0.6, "rationale": "risk budget"}
                },
                "total_equity_exposure": 0.4,
                "vix_regime": "normal"
            },
            "debate_state_artifact": {"final_reducer": {"authoritative_fields": {
                "controllers": {"topic-qqq": {"nodes": [
                    {"from": "bull", "payload": {
                        "report": "Breadth supports the QQQ upside.",
                        "evidence_refs": ["technical-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]
                    }},
                    {"from": "bear", "payload": {
                        "report": "Volatility remains a QQQ downside risk.",
                        "evidence_refs": ["jin10-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"]
                    }}
                ]}}
            }}}
        })
    }

    #[test]
    fn generates_all_nine_sections() {
        let report = build_human_readable_report(&full_state());
        for n in 1..=9 {
            assert!(
                report.contains(&format!("## {}. ", n)),
                "report missing section {}: {}",
                n,
                report
            );
        }
    }

    #[test]
    fn executive_summary_contains_rating_and_action() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("**Buy**"));
        assert!(report.contains("**Recommended Action:** Buy"));
        assert!(report.contains("72%"));
        assert!(report.contains("28%"));
    }

    #[test]
    fn bull_case_extracts_evidence_from_debate_turns() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("## 3. Bull Case"));
        assert!(report.contains("Earnings beat"));
    }

    #[test]
    fn bear_case_extracts_evidence_from_debate_turns() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("## 4. Bear Case"));
        assert!(report.contains("RSI overbought"));
    }

    #[test]
    fn trade_plan_uses_entry_price_and_stop_loss() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("| Entry | $45.00 |"));
        assert!(report.contains("| Stop Loss | $42.50 |"));
        assert!(report.contains("| Horizon | 1-5 trading days |"));
    }

    #[test]
    fn portfolio_allocation_renders_table() {
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("| TQQQ | 45.0% | Primary long exposure |"));
        assert!(report.contains("**Total Equity Exposure:** 45%"));
    }

    #[test]
    fn canonical_runtime_shape_renders_primary_asset_and_stree_evidence() {
        let state = canonical_runtime_state();
        let report = build_human_readable_report(&state);

        assert!(report.contains("Current rating: **Buy** (long: 74%, short: 26%)."));
        assert!(report.contains("**Recommended Action:** Buy"));
        assert!(report.contains("| Entry | 450.25 |"));
        assert!(report.contains("| Stop Loss | 430.5 |"));
        assert!(report.contains("Breadth supports the QQQ upside."));
        assert!(report.contains("Volatility remains a QQQ downside risk."));
        assert!(report.contains("Volatility can reverse the QQQ move."));
        assert!(report.contains(
            "technical-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        ));
        assert!(has_complete_report_projection(&state));

        let projection = report_projection(&state);
        assert_eq!(
            projection["research_plan"]["per_ticker"]["QQQ"]["rating"],
            "Buy"
        );
        assert!(has_complete_report_projection(&projection));
    }

    #[test]
    fn empty_state_does_not_crash() {
        let report = build_human_readable_report(&json!({}));
        assert!(report.contains("# N/A Strategy Report"));
        assert!(report.contains("## 1. Executive Summary"));
        assert!(report.contains("N/A"));
        assert!(report.contains("- No bull evidence recorded."));
        assert!(report.contains("- No bear evidence recorded."));
        assert!(report.contains("No allocation data available."));
    }

    #[test]
    fn partial_state_with_only_research_plan() {
        let state = json!({
            "ticker": "QQQ",
            "current_date": "2026-07-06",
            "research_plan": {
                "rating": "Hold",
                "long_probability": 0.5,
                "short_probability": 0.5,
                "confidence_basis": "data_insufficient",
                "hold_reason": "evidence_insufficient",
                "probability_rationale": "Neutral.",
                "plan": "Monitor."
            }
        });
        let report = build_human_readable_report(&state);
        assert!(report.contains("## 1. Executive Summary"));
        assert!(report.contains("## 9. Next Steps"));
        assert!(report.contains("- Monitor."));
        assert!(report.contains("- No bull evidence recorded."));
        assert!(report.contains("- No specific risks identified."));
        assert!(report.contains("Confidence basis: data_insufficient"));
        assert!(report.contains("Hold reason: evidence_insufficient"));
    }

    #[test]
    fn report_to_html_produces_well_formed_document() {
        let markdown = build_human_readable_report(&full_state());
        let html = report_to_html(&markdown);
        assert!(html.starts_with("<!doctype html>"));
        assert!(html.contains("<html>"));
        assert!(html.contains("<head>"));
        assert!(html.contains("<title>"));
        assert!(html.contains("<body>"));
        assert!(html.contains("</body></html>"));
        assert!(html.contains("<style>"));
    }

    #[test]
    fn report_to_html_renders_tables() {
        let markdown = build_human_readable_report(&full_state());
        let html = report_to_html(&markdown);
        assert!(html.contains("<table>"));
        assert!(html.contains("<th>"));
        assert!(html.contains("<td>"));
    }

    #[test]
    fn report_to_html_preserves_strikethrough_and_escapes_title() {
        let html = report_to_html("# QQQ <Risk> & Upside\n\n~~old thesis~~");
        assert!(html.contains("<title>QQQ &lt;Risk&gt; &amp; Upside</title>"));
        assert!(html.contains("<del>old thesis</del>"));
    }

    #[test]
    fn format_pct_handles_fraction_and_percent() {
        assert_eq!(format_pct(&json!(0.72)), "72%");
        assert_eq!(format_pct(&json!(72.0)), "72%");
        assert_eq!(format_pct(&json!("72%")), "72%");
        assert_eq!(format_pct(&json!(0.0)), "0%");
    }

    #[test]
    fn report_preserves_backward_compat_final_summary_format() {
        // The report should be valid Markdown with horizontal rules between sections.
        let report = build_human_readable_report(&full_state());
        assert!(report.contains("---"));
        assert!(report.contains("*Generated by Akzio Signal Intelligence"));
    }

    #[test]
    fn bull_evidence_direct_field_is_preferred() {
        let state = json!({
            "ticker": "TQQQ",
            "current_date": "2026-07-06",
            "debate_state_artifact": {
                "bull_evidence": ["Direct bull point A", "Direct bull point B"],
                "bear_evidence": ["Direct bear point A"]
            }
        });
        let report = build_human_readable_report(&state);
        assert!(report.contains("Direct bull point A"));
        assert!(report.contains("Direct bear point A"));
    }
}
