import SwiftUI

public enum AppLanguage: String, CaseIterable, Sendable, Identifiable {
    case system
    case english
    case simplifiedChinese

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .system: "System"
        case .english: "English"
        case .simplifiedChinese: "中文"
        }
    }

    public var resolved: AppLanguage {
        guard self == .system else { return self }
        return Locale.preferredLanguages.first?.hasPrefix("zh") == true
            ? .simplifiedChinese
            : .english
    }

    public var locale: Locale {
        Locale(identifier: resolved == .simplifiedChinese ? "zh-Hans" : "en")
    }
}

private struct AppLanguageKey: EnvironmentKey {
    static let defaultValue = AppLanguage.system.resolved
}

extension EnvironmentValues {
    public var appLanguage: AppLanguage {
        get { self[AppLanguageKey.self] }
        set { self[AppLanguageKey.self] = newValue.resolved }
    }
}

public enum L10n {
    public static func text(_ source: String, language: AppLanguage) -> String {
        guard language.resolved == .simplifiedChinese else { return source }
        return zhHans[source] ?? dynamicZhHans(source) ?? source
    }

    private static func dynamicZhHans(_ source: String) -> String? {
        let lower = source.lowercased()
        for (suffix, unit) in [("m ago", "分钟前"), ("h ago", "小时前"), ("d ago", "天前")] {
            guard lower.hasSuffix(suffix) else { continue }
            let value = lower.dropLast(suffix.count).trimmingCharacters(in: .whitespaces)
            if Int(value) != nil { return "\(value) \(unit)" }
        }

        let dateParts = source.split(separator: " ")
        let months = [
            "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6,
            "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12,
        ]
        if dateParts.count == 2,
           let month = months[String(dateParts[0])],
           let day = Int(dateParts[1])
        {
            return "\(month)月\(day)日"
        }

        if source.contains(" vs ") {
            return source.replacingOccurrences(of: " vs ", with: " 对比 ")
        }
        if source.hasPrefix("vs ") {
            return "对比 \(source.dropFirst(3))"
        }
        return nil
    }

    private static let zhHans: [String: String] = [
        "Overview": "总览", "Workflow": "工作流", "Intelligence": "智能议会",
        "Portfolio": "投资组合", "Outcome": "结果观测", "Learning": "学习",
        "Run Archive": "运行归档", "Scenario Gallery": "场景库", "Settings": "设置",
        "Live Overview": "运行总览", "Workflow Journey": "工作流旅程",
        "Intelligence Council": "智能议会", "Portfolio Performance": "组合表现",
        "Outcome Horizons": "结果期限", "Learning & Experience": "学习与经验",
        "Real-time Intelligence. Disciplined Execution.": "实时智能，纪律执行。",
        "End-to-end orchestration and decision intelligence.": "端到端编排与决策智能。",
        "Collaborative intelligence. Better outcomes.": "协作智能，改善结果。",
        "Multi-horizon outcomes with verifiable evidence.": "以可验证证据观测多期限结果。",
        "Turn outcomes into reusable learning assets.": "把结果沉淀为可复用学习资产。",
        "Complete ledger of runs, decisions and outcomes.": "完整追踪每次运行、决策与结果。",
        "Appearance": "外观", "Motion": "动效", "Model Display": "模型展示",
        "Mock Data Scenarios": "模拟数据场景", "Accessibility": "辅助功能",
        "Environment Info": "环境信息", "Language": "语言", "Theme": "主题",
        "Glass": "液态玻璃", "Glass Highlight": "玻璃高光", "Transparency": "透明度",
        "Liquid glass is used across cards, the status bar, inspectors and this panel.": "所有卡片、状态栏、检查器和此面板均使用液态玻璃。",
        "Density": "信息密度", "Rendering": "渲染", "Render Quality": "渲染质量",
        "Label Density": "标签密度", "Reasoning Visualization": "推理可视化",
        "Global Motion": "全局动效", "Motion Intensity": "动效强度",
        "Particle Density": "粒子密度", "Route Transition": "页面转场",
        "Reduce Motion": "减少动态效果", "Reduce Transparency": "降低透明度",
        "High Contrast": "高对比度", "Text Size": "文字大小",
        "Color-Independent Status": "非颜色状态提示", "Keyboard Focus Ring": "键盘焦点环",
        "VoiceOver Labels": "旁白标签", "Always On": "始终开启",
        "Total Equity": "总权益", "Today P&L": "今日盈亏",
        "Decision Confidence": "决策置信度", "Workflow Progress": "流程进度",
        "Signal Universe": "信号宇宙", "Latest Event": "最新事件",
        "Active Agents": "活跃智能体", "Health Snapshot": "健康快照",
        "Pipeline": "流程图", "Reasoning Intensity": "推理强度",
        "Model Gallery": "模型库", "Model Detail": "模型详情",
        "Equity Curve": "权益曲线", "Allocation": "配置", "Risk": "风险",
        "Allocation Flow": "配置流程", "Orders & Fills": "订单与成交",
        "Outcome Summary": "结果摘要", "Window Metrics": "期限指标",
        "Retrospective": "复盘", "Experience Timeline": "经验时间线",
        "Policy Transitions": "策略演化", "Lessons": "经验条目", "Impact": "影响",
        "Runs": "运行记录", "Run Preview": "运行预览", "Scenarios": "场景",
        "Completed": "已完成", "Running": "运行中", "Queued": "排队中",
        "Waiting": "等待中", "Observing": "观测中", "Failed": "失败",
        "Cancelled": "已取消", "Not Triggered": "未触发", "Not Applicable": "不适用",
        "Unavailable": "不可用", "Stale": "数据陈旧", "Succeeded": "成功",
        "Market Open": "市场开放", "Market Closed": "市场关闭",
        "Data Live": "数据实时", "Data Stale": "数据陈旧", "Data Queued": "数据排队中",
        "Health": "健康度", "Copy Run ID": "复制运行 ID",
        "Reveal Run in Archive": "在归档中显示", "Open Settings": "打开设置",
        "View Details": "查看详情", "Open in New Window": "在新窗口打开",
        "Close": "关闭", "Display only": "只读展示",
        "Table": "表格", "Cards": "卡片", "Purpose": "用途", "Status": "状态",
        "More Filters": "更多筛选", "Clear Filters": "清除筛选",
        "No runs match filters": "没有符合筛选条件的运行记录",
        "Mode": "模式",
        "Use Mock Data": "使用模拟数据",
        "Connect Observer": "连接观察器",
        "Rust Observer": "Rust 观察器",
        "Observer token": "观察器令牌",
        "Source": "数据源",
        "Tasks": "任务",
        "Run Status": "运行状态",
        "Mock": "模拟数据",
        "Connecting": "连接中",
        "Connected": "已连接",
        "Offline": "离线",
        "Daemon": "守护进程",
        "Frozen": "已冻结",
        "Store Alerts": "存储告警",
        "Event Cursor": "事件游标",
        "Observer snapshot synchronized": "观察器快照已同步",
        "Unavailable from observer": "观察器未提供此数据",
        "This page stays unavailable until Rust publishes its durable data.": "Rust 尚未发布对应的持久化数据，因此本页保持不可用。",
        "Toggle navigation": "切换导航",
        "Run controls": "运行菜单",
        "Display only — build never writes Store": "只读展示——应用绝不写入 Store",
        "Elevated risk band": "风险区间升高",
        "Page": "页",
        "success": "成功率",
        "Dismiss settings": "关闭设置",
        "Show": "显示",
        "Target": "目标",
        "Counterfactual": "反事实",
        "Diagnostic Gaps": "诊断缺口",
        "None recorded": "暂无记录",
        "P&L Impact": "盈亏影响",
        "Frozen Clock": "冻结时钟",
        "Scenario": "场景",
        "Stage Inspector": "阶段检查器",
        "durable tasks": "持久化任务",
        "Reconciliation": "对账",
        "No fills yet": "暂无成交",
        "Position sizing constrained": "仓位规模受限",
        "Go to Learning": "前往学习",
        "Equity curve": "权益曲线",
        "Reasoning intensity": "推理强度",
        "ELAPSED": "已用时",
        "TOPOLOGY": "拓扑",
        "MODEL": "模型",
        "SESSION": "会话",
        "HEALTH": "健康度",
        "Live": "活跃",
        "Blocked": "已阻断",
        "Low": "低",
        "Medium": "中",
        "High": "高",
        "Planner": "规划器",
        "Evidence Gate": "证据门",
        "Analyst 1": "分析员 1",
        "Analyst 2": "分析员 2",
        "Analyst 3": "分析员 3",
        "Critic": "评审者",
        "Synthesizer": "综合者",
        "Decision Gate": "决策门",
        "Execution Gate": "执行门",
        "Paper Commit": "Paper 提交",
        "Reconcile": "对账",
        "Evaluate": "评估",
        "Portfolio VaR (95%)": "组合 VaR（95%）",
        "Max Drawdown": "最大回撤",
        "Leverage Used": "已用杠杆",
        "Data Quality": "数据质量",
        "System Load": "系统负载",
        "No Executable Order": "无可执行订单",
        "Targets already within tolerance; nothing submitted.": "目标已在容差范围内；未提交订单。",
        "Evidence Gate Passed": "证据门已通过",
        "Execution Gate Passed": "执行门已通过",
        "Risk within limits. Proceeding to execution.": "风险在限制内，继续执行。",
        "Critic Triggered": "评审者已触发",
        "Material conflict detected in sector exposure.": "检测到行业敞口存在重大冲突。",
        "Decision Gate Blocked": "决策门已阻断",
        "Turnover limit exceeded; execution withheld.": "换手率超限，执行已暂停。",
        "Quote Snapshot Stale": "报价快照已过期",
        "Market data older than freshness budget.": "市场数据已超过新鲜度时限。",
        "12 normalized documents with valid provenance.": "12 份标准化文档具有有效溯源。",
        "roles": "个角色",
        "WORKSPACE": "工作区",
        "SYSTEM": "系统",
        "Analyst-1": "分析员-1",
        "Analyst-2": "分析员-2",
        "Analyst-3": "分析员-3",
        "PLAN COMPILED": "规划已完成",
        "MARKET STRUCTURE": "市场结构",
        "CAPITAL FLOW": "资金流",
        "SENTIMENT & POSITIONING": "情绪与仓位",
        "CONVERGING CLAIMS": "汇总论点",
        "NO MATERIAL CONFLICT DETECTED": "未检测到重大冲突",
        "System": "跟随系统",
        "English": "English",
        "Application & Core": "应用与核心",
        "Three deep-grey variants; warmth only.": "三种深灰主题，仅调整冷暖倾向。",
        "Accent": "强调色",
        "Fixed by design: gold carries state, coral is reserved for actions that cannot be undone.": "强调色由设计固定：金色表达状态，珊瑚色仅用于不可撤销操作。",
        "Primary": "主色",
        "Action": "操作色",
        "Locked": "已锁定",
        "Layout": "布局",
        "Scales card padding and table row height.": "调整卡片内边距与表格行高。",
        "Higher reveals more of the desktop behind the window.": "值越高，窗口后方的桌面越清晰。",
        "Dark": "深色",
        "Dusk": "暮色",
        "Midnight": "午夜",
        "Compact": "紧凑",
        "Comfortable": "舒适",
        "Spacious": "宽松",
        "Auto": "自动",
        "Minimal": "最少",
        "Full": "完整",
        "Rust Core": "Rust 核心",
        "The bundled Paper-only daemon starts with the App and stops on Quit.": "内置的仅 Paper 守护进程随 App 启动，并在退出 App 时停止。",
        "Core": "核心",
        "Observer": "观测器",
        "Paper Approval": "Paper 审批",
        "Store": "存储",
        "Required Credentials": "必需凭证",
        "Configuration is saved in ~/.akzio/config.toml with owner-only permissions.": "配置保存在 ~/.akzio/config.toml，并限制为仅当前用户可读写。",
        "Model Routing": "模型路由",
        "Defaults apply globally; each model-mediated Rust stage can override model, reasoning effort, and response language.": "默认配置全局生效；每个由模型驱动的 Rust 阶段都可覆盖模型、思考强度和返回语言。",
        "Optional Evidence": "可选证据",
        "Missing optional sources do not prevent Core startup.": "缺少可选数据源不会阻止核心启动。",
        "FRED API key": "FRED API 密钥",
        "SEC user agent": "SEC 用户代理",
        "Save & Restart Core": "保存并重启核心",
        "Clear Credentials": "清除凭证",
        "Approval remains a separate Rust CLI action; Observatory never writes it.": "审批仍由独立的 Rust CLI 完成；Observatory 不会写入审批。",
        "Recent Core Output": "最近核心输出",
        "LLM Gateway base URL": "LLM 网关基础 URL",
        "LLM API key": "LLM API 密钥",
        "Alpaca API key": "Alpaca API 密钥",
        "Alpaca API secret": "Alpaca API Secret",
        "Default": "默认",
        "Fallback for model-mediated stages without an explicit route.": "没有独立路由的模型阶段使用此默认配置。",
        "Model": "模型",
        "Reasoning": "思考强度",
        "Response Language": "返回语言",
        "configured; enter to replace": "已配置；输入新值以替换",
        "None": "无",
        "Xhigh": "超高",
        "Max": "最高",
        "Stopped": "已停止",
        "Needs Configuration": "需要配置",
        "Starting": "启动中",
        "Waiting for Ready": "等待就绪",
        "Ready": "已就绪",
        "Stopping": "停止中",
        "Valid": "有效",
        "Expired": "已过期",
        "Mismatched": "不匹配",
        "Missing": "缺失",
        "Global": "全局",
        "Off stops ambient orbits, particles and page travel.": "关闭后停止环境轨迹、粒子和页面位移动效。",
        "Scales travel distance and particle count.": "调整位移距离和粒子数量。",
        "Signal particles per edge on the Universe and DAG.": "调整信号宇宙与 DAG 每条边的粒子数量。",
        "Route Transition Strength": "页面转场强度",
        "0 hands pages over with a plain crossfade.": "设为 0 时仅使用简单淡入淡出切换页面。",
        "Reduce Motion Preview": "减少动态效果预览",
        "Reduced motion keeps opacity and colour cues and drops travel to at most 6pt.": "减少动态效果会保留透明度与颜色提示，并将位移限制在 6pt 以内。",
        "Reduced": "已减少",
        "Ambient loops running": "环境动效运行中",
        "Ambient loops stopped": "环境动效已停止",
        "Travel": "位移",
        "Caps particles, nodes and frame interval.": "限制粒子数、节点数与帧间隔。",
        "Auto hides labels when nodes crowd.": "节点拥挤时自动隐藏标签。",
        "Draws the intensity orbit around active agents.": "在活跃智能体周围绘制推理强度轨迹。",
        "Active Budget": "当前渲染预算",
        "Universe Particles": "宇宙粒子",
        "Path Particles": "路径粒子",
        "Frame Interval": "帧间隔",
        "Ambient Loops": "环境循环",
        "Paused": "已暂停",
        "Motion and Materials": "动效与材质",
        "System settings win: an override can only add restrictions, never remove them.": "系统设置优先；App 覆盖只能增加限制，不能移除限制。",
        "Near-solid surfaces and explicit borders.": "使用接近实色的表面和明确边框。",
        "Reading": "阅读",
        "Scales body and label text; monospaced numerals stay aligned.": "缩放正文与标签文字；等宽数字仍保持对齐。",
        "Every status also carries a glyph and a word.": "每个状态同时使用图标和文字表达。",
        "Navigation": "导航",
        "Gold focus ring on the focused control.": "当前焦点控件显示金色焦点环。",
        "Build": "构建信息",
        "System: on — already applied": "系统：已开启并生效",
        "System: off": "系统：关闭",
        "Run": "运行",
        "Running…": "运行中…",
        "Start one real-model run in Debug safety mode. Paper submission remains scheduler-owned.": "启动一次真实模型运行（Debug 安全模式）。Paper 提交仍仅由调度器控制。",
        "Real model · Debug safety mode": "真实模型 · Debug 安全模式",
        "Run is unavailable in Mock mode": "Mock 模式下无法运行",
        "Starting Rust Core…": "正在启动 Rust 核心…",
        "Run submitted": "运行已提交",
        "Debug": "调试",
        "Paper": "Paper",
        "Paper Dry Run": "Paper 演练",
        "Replay": "回放",
        "Shadow": "影子运行",
        "Market": "市场",
        "Data": "数据",
        "Latency": "延迟",
        "Core Readiness": "核心就绪度",
        "Risk, data and process vitals": "风险、数据与进程生命体征",
        "OK": "正常",
        "Positions, P&L and exposure in one screen.": "在一个页面查看持仓、盈亏与敞口。",
        "Actual vs Target": "实际与目标",
        "Signal to fill": "从信号到成交",
        "Attributed sealed outcomes": "已封存结果的归因效用",
        "Promoted sealed retrospectives": "已晋升的封存复盘",
        "Memory lifecycle and canary ladder": "记忆生命周期与金丝雀阶梯",
        "Rings & Bars": "环图与条形图",
        "19 states, tone + symbol + label": "19 种状态，包含色调、图标与标签",
        "Status Vocabulary": "状态词汇",
        "Transition Matrix": "转移矩阵",
        "every pair reversible": "每对均可逆",
        "never rendered as zero": "绝不渲染为伪零值",
        "nil progress draws dashed track": "缺失进度使用虚线轨道",
        "Deterministic mock scenarios and component library.": "用于视觉验证的确定性 Mock 场景与组件库。",
        "No canonical Outcome is available yet": "暂无规范 Outcome 数据",
        "No canonical learning artifacts are available yet": "暂无规范学习产物",
        "Learning Evidence": "学习证据",
        "Learning appears only after real Paper outcomes are sealed; Debug runs never create learning data.": "只有真实 Paper 结果封存后才会出现学习数据；Debug 运行不会生成学习数据。",
        "Awaiting sealed trading-session evidence": "等待已封存的交易会话证据",
        "Sealed from canonical Paper evidence": "已由规范 Paper 证据封存",
        "Analysis Record": "分析记录",
        "Observer-safe summaries, tool lifecycle, validated LLM output, and conclusion. Hidden reasoning and secret-bearing arguments remain excluded.": "仅展示 Observer 安全摘要、工具生命周期、经校验的 LLM 输出与结论；隐藏推理及含秘密参数仍被排除。",
        "Natural-language LLM research, tool lifecycle, and Rust-validated output. Hidden reasoning and secret-bearing arguments remain excluded.": "展示 LLM 自然语言研究稿、工具生命周期和经 Rust 校验的输出；隐藏推理及含秘密参数仍被排除。",
        "Rust-owned stage; no LLM or tool record applies.": "此阶段由 Rust 负责，不适用 LLM 或工具记录。",
        "No observed analysis record is available for this node.": "该节点暂无可观测分析记录。",
        "Analysis Summary": "分析摘要",
        "Reasoning Summary": "思考摘要",
        "Generating reasoning summary…": "正在生成思考摘要…",
        "Streaming": "生成中",
        "Copy": "复制",
        "Less": "收起",
        "More": "展开",
        "Analysis": "分析",
        "Tool": "工具",
        "LLM": "LLM",
        "Rust": "Rust",
        "Conclusion": "结论",
        "Observed Topics": "已观测议题",
        "Derived from durable deliberation and validated artifacts": "基于持久化审议与经验证产物生成",
        "No observed topics are available.": "暂无已观测议题。",
        "Analysis Process": "分析过程",
        "Chronological Observer record · no hidden reasoning": "按时间排序的 Observer 记录 · 不含隐藏推理",
        "No analysis process has been observed.": "暂未观测到分析过程。",
        "Observed Intelligence": "已观测智能分析",
        "No observed analysis yet": "暂无已观测分析",
        "Topics and analysis records appear only after Rust emits Observer-safe trajectory or validated artifacts.": "只有 Rust 输出 Observer 安全轨迹或经验证产物后，才会显示议题与分析记录。",
        "Topics": "议题",
        "Records": "记录",
        "Topic": "议题",
        "Issue": "问题",
        "Alternative": "备选方案",
        "Deliberation": "审议",
        "Provider": "提供方",
        "Turn": "调用轮次",
        "Tool Calls": "工具调用",
        "No tool calls — the LLM returned its result without invoking a tool.": "未调用工具——LLM 未调用工具即返回结果。",
        "Input Tokens": "输入词元",
        "Output Tokens": "输出词元",
        "Confidence": "置信度",
        "Hard Blockers": "硬阻断项",
        "Soft Warnings": "软警告",
        "Alternatives": "备选方案",
        "Uncertainties": "不确定项",
        "Active": "活跃",
        "Critical Alerts": "严重告警",
        "Observation": "观测进度",
        "Trading Sessions": "交易会话",
        "Workflow graph": "工作流关系图",
        "Zoom Out": "缩小",
        "Zoom In": "放大",
        "Fit": "适配画布",
        "Reset View": "重置视图",
        "Labels": "标签",
        "Particles": "粒子",
        "Grid": "网格",
        "Critical Path": "关键路径",
        "Collapse Optional": "收起可选节点",
        "Sequential": "顺序",
        "Parallel": "并行",
        "Optional": "可选",
        "Loop Back": "回环",
        "Conflict": "冲突",
        "Equity": "账户权益",
        "Today": "今日盈亏",
        "Unrealized": "未实现盈亏",
        "Realized": "已实现盈亏",
        "Elevated": "风险升高",
        "Within limits": "限制内",
        "WITHIN LIMITS": "限制内",
        "Beta": "贝塔",
        "BETA": "贝塔",
        "Volatility": "波动率",
        "Leverage": "杠杆",
        "PORTFOLIO": "投资组合",
        "Time": "时间",
        "Asset": "资产",
        "Side": "方向",
        "Type": "类型",
        "Qty": "数量",
        "Limit": "限价",
        "State": "状态",
        "Price": "价格",
        "Venue": "成交场所",
        "Target Weights": "目标权重",
        "Delta": "差值",
        "Order Intent": "订单意图",
        "Gate": "门控",
        "Broker": "券商",
        "Reached": "已到达",
        "Not Reached": "未到达",
        "No executable order was produced for this run": "本次运行未生成可执行订单",
        "Transaction Cost": "交易成本",
        "Slippage": "滑点",
        "Net Return": "净收益",
        "Utility": "效用",
        "Calibration": "校准度",
        "Evidence Completeness": "证据完整度",
        "Risk Recall": "风险召回率",
        "Metrics appear once the window seals": "窗口封存后显示指标",
        "This horizon has not sealed yet": "该期限尚未封存",
        "Benchmark": "基准",
        "Alpha": "超额收益",
        "Win Rate": "胜率",
        "Profit Factor": "盈利因子",
        "Sharpe": "夏普比率",
        "No sealed outcome to learn from yet": "暂无可供学习的已封存结果",
        "Open Learning & Experience": "打开学习与经验",
        "No canonical outcome available": "暂无规范 Outcome 数据",
        "WINDOW NOT REACHED": "窗口尚未到达",
        "Window not reached": "窗口尚未到达",
        "Last 30 Trading Sessions": "最近 30 个交易会话",
        "Last 30 days vs previous 30": "最近 30 天对比此前 30 天",
        "retrospectives": "条复盘",
        "From": "来源",
        "Retrospectives require a sealed Paper outcome": "复盘需要已封存的 Paper 结果",
        "Retrospective model was unavailable for this run": "本次运行的复盘模型不可用",
        "Lesson Candidate": "经验候选",
        "Hide Detail": "收起详情",
        "Show Detail": "显示详情",
        "events": "个事件",
        "No experience recorded for this run yet": "本次运行暂无经验记录",
        "session": "会话",
        "Net Impact": "净影响",
        "Stability": "稳定度",
        "Exposure": "暴露比例",
        "Top Impact Areas": "主要影响领域",
        "Attributed Utility": "归因效用",
        "Lessons Created": "已创建经验",
        "Policies Evolved": "已演化策略",
        "No change": "无变化",
        "this window": "本窗口",
        "Research": "研究",
        "Evidence": "证据",
        "Decision": "决策",
        "Execution": "执行",
        "Contract": "契约",
        "What Worked": "有效做法",
        "What Failed": "失败原因",
        "Mixed": "混合",
        "Unresolved": "未解决",
        "Candidate": "候选",
        "Proven": "已验证",
        "Contested": "有争议",
        "Retired": "已停用",
        "Memory": "记忆",
        "Canary 10%": "金丝雀 10%",
        "Canary 25%": "金丝雀 25%",
        "Canary 50%": "金丝雀 50%",
        "Promoted from sealed retrospectives": "由已封存复盘晋升",
        "Attributed to sealed outcomes": "归因于已封存结果",
        "No lesson candidates for this window": "本窗口暂无经验候选",
        "No canonical learning available": "暂无规范学习数据",
        "Run ID": "运行 ID",
        "Current Stage": "当前阶段",
        "Duration": "持续时间",
        "Result": "结果",
        "Summary": "摘要",
        "Stage Progress": "阶段进度",
        "Close preview": "关闭预览",
        "Search runs": "搜索运行记录",
        "All Purposes": "全部用途",
        "All Statuses": "全部状态",
        "Search": "搜索",
        "shown": "已显示",
        "matching": "条匹配",
        "Success": "成功率",
        "sorted by": "排序依据",
        "runs": "条运行",
        "of": "共",
        "Not started — no result exists yet.": "尚未开始，因此暂无结果。",
        "Leased by a worker; execution has not begun.": "已由 worker 租约接管，但执行尚未开始。",
        "Result is sealed after the outcome horizon closes.": "结果将在观测期限结束后封存。",
        "Decision sealed. Awaiting the outcome horizon.": "决策已封存，等待结果观测期限。",
        "Sealed outcome for the run's canonical horizon.": "运行的规范期限结果已封存。",
        "Sealed with an execution rejection on record.": "结果已封存，并记录了执行拒绝。",
        "Run ended in error; no outcome was sealed.": "运行因错误结束，未封存结果。",
        "Cancelled before the horizon could seal.": "在期限封存前已取消。",
        "Paper Running — Synthesizer Active": "Paper 运行中 — 综合者活跃",
        "Plan compiled": "规划已完成",
        "Market structure": "市场结构",
        "Capital flow": "资金流",
        "Sentiment & positioning": "情绪与仓位",
        "Converging claims": "汇总论点",
        "Synthesis": "综合分析",
        "No material conflict detected": "未检测到重大冲突",
        "Claims are consistent with evidence set; proceeding along critical path.": "论点与证据集一致，沿关键路径继续。",
        "Claims are consistent with the evidence set; proceeding along the critical path.": "论点与证据集一致，沿关键路径继续。",
        "Hold current weights": "维持当前权重",
        "Rotate into QQQ": "转向 QQQ",
        "Trim leveraged exposure": "削减杠杆敞口",
        "Rate path repricing": "利率路径重新定价",
        "Semiconductor demand": "半导体需求",
        "Liquidity concentration": "流动性集中度",
        "Earnings dispersion": "盈利分化",
        "1 Trading Session": "1 个交易会话",
        "3 Trading Sessions": "3 个交易会话",
        "5 Trading Sessions": "5 个交易会话",
        "Accepted": "已接受",
        "Analyst": "分析员",
        "Cash": "现金",
        "Sealed after 1 trading session": "在 1 个交易会话后封存",
        "Sealed after 3 trading sessions": "在 3 个交易会话后封存",
        "Sealed after 5 trading sessions": "在 5 个交易会话后封存",
        "Completed · Rejected": "已完成 · 已拒绝",
        "Completed · Execution Rejected": "已完成 · 执行已拒绝",
        "Elapsed": "已用时",
        "Topology": "拓扑",
        "Session": "会话",
        "active": "活跃拓扑",
        "stages": "个阶段",
        "paper_scheduler_fail_closed": "Paper 调度器安全关闭",
        "Artifact Committed": "产物已提交",
        "Task Succeeded": "任务已成功",
        "Task Started": "任务已启动",
        "Task Failed": "任务失败",
        "Task Cancelled": "任务已取消",
        "Context Manifest Created": "上下文清单已创建",
        "Agent Turn Started": "模型调用已开始",
        "Agent Turn Completed": "模型调用已完成",
        "Deliberation Note Created": "审议记录已创建",
        "Workflow Patched": "工作流已更新",
        "Run lifecycle": "运行生命周期",
        "Task": "任务",
        "Rust-owned gate.evidence": "Rust 负责的证据门控",
        "Rust-owned gate.decision": "Rust 负责的决策门控",
        "Rust-owned gate.execution": "Rust 负责的执行门控",
        "Rust-owned gate.reconcile": "Rust 负责的对账门控",
        "Rust-owned gate.evaluate": "Rust 负责的评估门控",
        "Started": "已开始",
        "Called": "已调用",
    ]
}
