//! Research prompt ownership: complete role documents and typed phase builders.
//! Runtime reads frozen governance/role blobs; these sources install new Contracts.

// 这个 Rust 模块只负责把已登记的 governance/role 文本装进 PromptBundle，并把
// 阶段协议交给 typed builders；它不把 Markdown 内容变成权限。Contract、预算、
// ContextManifest 和 submit_result 工具面仍由 Rust Runtime 决定，Outcome 的 Draft
// 与受控读取也不会因为 role_prompt 返回成功而提前完成。
use super::*;
mod phases;
pub(super) use phases::*;

pub(super) const SHARED_GOVERNANCE_PROMPT: &str = include_str!("shared.md");
pub(super) const ANALYST_FRESHNESS_GUIDANCE: &str = "\n\n候选 freshness v21：使用 Rust 的 time_basis.available_at、latest_completed_session 和 decision cutoff 评估内容新鲜度。检索时间本身绝不是新鲜度证明。将过期或缺失的覆盖报告为有范围的 evidence_gaps。\n";

pub(super) fn role_prompt(purpose: &str) -> ResearchResult<String> {
    // purpose 是安装 Contract 的稳定身份，只能命中当前允许的角色；未知值返回
    // 错误而不是读取任意路径。include_str! 的 Markdown 字节由 prompt registry 冻结，
    // 本函数只复制为 owned String 供后续组合，不修改 Prompt 文本。
    let role = match purpose {
        RESEARCH_ANALYST_RECIPE_ID => include_str!("roles/analyst.md"),
        RESEARCH_CRITIC_RECIPE_ID => include_str!("roles/critic.md"),
        RESEARCH_SYNTHESIZER_RECIPE_ID => include_str!("roles/synthesizer.md"),
        akzio_domain::RESEARCH_PROPOSAL_REVIEWER_RECIPE_ID => {
            include_str!("roles/proposal_reviewer.md")
        }
        LEARNING_OUTCOME_WORKER_RECIPE_ID => include_str!("roles/outcome.md"),
        _ => {
            return Err(ResearchError::UnexpectedActiveContractPurpose(
                purpose.to_owned(),
            ))
        }
    };
    Ok(role.to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn continuation_preserves_phase_version_and_repair_boundaries() {
        assert!(continuation_instruction(AgentTurnPhase::Draft, 53, false).is_none());
        assert!(continuation_instruction(AgentTurnPhase::Draft, 53, true).is_none());
        let current = continuation_instruction(AgentTurnPhase::Submit, 53, false).unwrap();
        assert!(current.contains("retriable 的阻断性缺口必须设置 retriable=true，并提供非空且受治理的 supplemental_needs"));
        for version in [52, 53] {
            let repair = continuation_instruction(AgentTurnPhase::Submit, version, true).unwrap();
            assert!(repair.contains("一次有界的修复轮次"));
            assert!(repair.contains("不要调用读取工具，也不要添加新证据"));
        }
    }

    #[test]
    fn request_preserves_authority_prefix_and_does_not_reinterpret_data() {
        let budget = TaskBudget {
            max_input_tokens: 48000,
            max_output_tokens: 5000,
            max_wall_time_secs: 120,
            max_tool_calls: akzio_domain::budget::ToolCallLimit::Limited(2),
        };
        let ledger = r#"[{"artifact_id":"{governance}","kind":"claim"}]"#;
        let render = || {
            outcome_request_prompt(
                "governance",
                "role {reference_ledger}",
                "简体中文",
                ledger,
                &budget,
            )
            .unwrap()
        };
        let claim = render();
        assert!(claim.starts_with("governance\n\nrole {reference_ledger}\n\n在 Draft 阶段"));
        assert!(claim.contains(ledger));
        assert!(!claim.contains("提交不变量："));
        let synthesis = render();
        assert!(!synthesis.contains("提交不变量："));
        assert!(synthesis.ends_with("Draft 和 Submit 共享该预算。\n"));
        assert!(synthesis.contains(&serde_json::to_string(&budget).unwrap()));
    }

    #[test]
    fn extracted_roles_preserve_frozen_bundle_bytes() {
        // Captured from the pre-extraction assembly, not generated by the new renderer.
        // research.analyst and research.critic were re-captured on 2026-09-22
        // when observed structured-submission constraints were made explicit;
        // Synthesizer and Reviewer were recaptured for Contract 69 / bundle 38
        // structured issues and scoped revision. Outcome remains unchanged.
        // An unintended prompt edit must still fail here.
        let expected = [
            (
                RESEARCH_ANALYST_RECIPE_ID,
                "8f0734cdc65a413fed4a74675193dd67c4189fd58ad7c065032c06d43eec5acc",
            ),
            (
                RESEARCH_CRITIC_RECIPE_ID,
                "a75315c9c0d32095110da72aac53e79e76011628780d261aeb1fae21daab79b5",
            ),
            (
                RESEARCH_SYNTHESIZER_RECIPE_ID,
                "fd685630f6580204674e162ec77e4acea9d9a0c5ab92a7120813f8bef70f1a93",
            ),
            (
                akzio_domain::RESEARCH_PROPOSAL_REVIEWER_RECIPE_ID,
                "00a2abe1bc77bde1c5e9e0eda16d096e0952fe440d109dad9bb09e553e372d2c",
            ),
            (
                LEARNING_OUTCOME_WORKER_RECIPE_ID,
                "123249e2bf0f227c2d292df36b9e5a8b50520eadea0e8c07d735dbfe8f4f0308",
            ),
        ];
        for (purpose, hash) in expected {
            assert_eq!(
                akzio_domain::ContentHash::of_bytes(role_prompt(purpose).unwrap().as_bytes())
                    .as_str(),
                hash,
                "{purpose}"
            );
        }
        assert!(role_prompt("unknown").is_err());
    }
}
