include!("research_tests/support.rs");
include!("research_tests/capabilities.rs");
include!("research_tests/capability_drift.rs");
include!("research_tests/agent_turn_models.rs");
include!("research_tests/contract_support.rs");
include!("research_tests/contract_schema.rs");
include!("research_tests/runtime_guards.rs");
include!("research_tests/budget.rs");
include!("research_tests/recovery.rs");
